name: Test on Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        
    - name: Install dependencies
      run: |
        cd PWManager.UnitTests
        dotnet restore

    - name: Run Unit Tests
      run: |
        cd PWManager.UnitTests
        dotnet test --logger "console;verbosity=detailed"
